# Jobs to run on PR, tests, lint, check, etc.
name: Default branch verification

on:
  push:
    branches:
      - publishing

jobs:

  test-default:
    name: Test default branch
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-default
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Prepare to publish
        run: |
          echo '${{secrets.GPG_KEY_CONTENTS}}' | base64 -d > publish_key.gpg
          gpg --quiet --batch --yes --decrypt --passphrase="${{secrets.GPG_SECRET_PASSPHRASE}}" \
            --output ${{github.WORKSPACE}}/secret.gpg publish_key.gpg
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Publish with Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: |
            uploadArchives closeRepository
              -Psigning.secretKeyRingFile=${{github.WORKSPACE}}/secret.gpg
              -Psigning.password=${{secrets.SIGNING_PASSWORD}}
              -PossrhUsername=${{secrets.OSSRH_USERNAME}}
              -PossrhPassword=${{secrets.OSSRH_PASSWORD}}
              -Pversion=${{ env.RELEASE_VERSION }}
          wrapper-directory: lib
          build-root-directory: lib
